image: python:3.9

variables:
  AZURE_WEBAPP_NAME: "platform-chatbot"
  AZURE_RESOURCE_GROUP: "game-analytics-rg"

stages:
  - build
  - deploy

before_script:
  - python -V
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Building application..."
    - pip install -r requirements.txt
  artifacts:
    paths:
      - app/
      - data/
      - requirements.txt
      - query_data.py
      - populate_database.py
      - get_embedding_function.py
      - startup.sh
      - .env
  only:
    - main

deploy:
  stage: deploy
  image: python:3.9
  before_script:
    # Install Azure CLI
    - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
    - python -V
    - pip install -r requirements.txt
  script:
    - echo "Deploying to Azure App Service..."

    # Login to Azure
    - az login --service-principal --username "$AZURE_SP_ID" --password "$AZURE_SP_PASSWORD" --tenant "$AZURE_TENANT_ID"

    # Create deployment package
    - apt-get update && apt-get install -y zip
    - zip -r deployment.zip . -x "*.git*"

    # Deploy to Azure App Service
    - |
      for i in {1..3}; do
        if az webapp deployment source config-zip --resource-group "$AZURE_RESOURCE_GROUP" --name "$AZURE_WEBAPP_NAME" --src deployment.zip --timeout 1800; then
          break
        fi
        echo "Deployment attempt $i failed, retrying..."
        sleep 30
      done

    # Configure app settings
    - |
      az webapp config appsettings set \
      --resource-group "$AZURE_RESOURCE_GROUP" \
      --name "$AZURE_WEBAPP_NAME" \
      --settings WEBSITES_PORT=8000

    # Set startup command
    - |
      az webapp config set \
        --resource-group "$AZURE_RESOURCE_GROUP" \
        --name "$AZURE_WEBAPP_NAME" \
        --startup-file "startup.sh"

  environment:
    name: production
    url: https://$AZURE_WEBAPP_NAME.azurewebsites.net
  only:
    - main
