#####################
#    DEVELOPMENT    #
#####################

# Health check
GET http://localhost:8000/health

####

# Chat request
POST http://localhost:8000/chat
Content-Type: application/json

{
  "message": "What is the monopoly game all about?"
}


#####################
#    PRODUCTION     #
#####################

# Health check
GET https://platform-chatbot.azurewebsites.net/health

#######

# Chat endpoint
POST https://platform-chatbot.azurewebsites.net/chat
Content-Type: application/json

{
    "message": "How can I use the registration page?"
}